baseURL: https://al002.github.io
languageCode: en-us
title: Elixir in action notes
theme: "PaperMod"

params:
  disableSpecial1stPost: true
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

